version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: userstart
      POSTGRES_DB: db_start
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-conf:/etc/postgresql
    networks:
      - db-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-net

networks:
  db-net: